package com.infobarbosa.mytasks.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName="tasks")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Task {
    

    @DynamoDBHashKey(attributeName = "taskId")
    @DynamoDBAutoGeneratedKey
    private String taskId;
    
    @DynamoDBAttribute
    private String description;
}
